version: '3.8'
services:
  tinyurl_api:
    build: docker/php
    container_name: tinyurl_api
    user: "${UID}:${GID}"
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: tinyurl_api
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG?}
    working_dir: /var/www/html
    volumes:
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www/html
    ports:
      - '9000:80'
    depends_on:
      - tinyurl_nginx
    extra_hosts:
      - host.docker.internal:host-gateway

  #Nginx Service
  tinyurl_nginx:
    image: nginx:alpine
    container_name: tinyurl_nginx
    restart: unless-stopped
    tty: true
    ports:
      - '${APP_PORT}:80'
      - '${APP_SECURE_PORT}:443'
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html/
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    command: [nginx-debug, '-g', 'daemon off;']
